name: PR Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests & coverage
        run: npm run test:ci

      - name: Install jq for parsing JSON
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract coverage summary
        id: coverage
        run: |
          COVERAGE=$(jq . coverage/coverage-summary.json)
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

       - name: Generate Markdown summary
        id: summary
        shell: bash
        run: |
          # pull test metrics
          TOTAL=$(jq .summary.total test-results.json)
          PASS=$(jq .summary.success test-results.json)
          FAIL=$(jq .summary.failed test-results.json)

          # pull coverage metrics
          STMT=$(jq .total.statements.pct coverage/coverage-summary.json)
          BRNC=$(jq .total.branches.pct coverage/coverage-summary.json)
          FUNC=$(jq .total.functions.pct coverage/coverage-summary.json)
          LINE=$(jq .total.lines.pct coverage/coverage-summary.json)

          # build a Markdown table in a heredoc
          read -r -d '' TABLE <<EOF
          | 📊 Metric              | 🔢 Value       |
          | ---------------------- | ------------: |
          | ✅ Tests Passed        | ${PASS}/${TOTAL} |
          | ❌ Tests Failed        | ${FAIL}         |
          | 📑 Statements Coverage | ${STMT}%        |
          | 🌿 Branches Coverage   | ${BRNC}%        |
          | 🔧 Functions Coverage  | ${FUNC}%        |
          | 📋 Lines Coverage      | ${LINE}%        |
          EOF

          # export it as a multiline step output
          echo "report<<EOF" >> $GITHUB_OUTPUT
          echo "$TABLE"           >> $GITHUB_OUTPUT
          echo "EOF"              >> $GITHUB_OUTPUT

      - name: Comment summary to PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🛠️ CI Test & Coverage Report
            ${{ steps.summary.outputs.report }}